import { useState, useEffect, useRef, useId } from "react";
import "./App.css";

function App() {
    // here we will have our articles array
    const articles = [
        {
            title: "title1",
            url: "#",
            date: "3/4/2002",
        },
        {
            title: "title2",
            url: "#",
            date: "3/5/2002",
        },
        {
            title: "title3",
            url: "#",
            date: "3/6/2002",
        },
        {
            title: "title4",
            url: "#",
            date: "1/4/2005",
        },
        {
            title: "title5",
            url: "#",
            date: "2/4/2009",
        },
    ];
    return (
        <>
            <h1>Beyond Chat Blogs</h1>
            <p>These blogs are auto generated by groq AI</p>
            <hr />
            {/* {articles.map((article) => {
                return <PostCard article={article} />;
            })} */}
        </>
    );
}

export default App;
